# Generated by Django 4.1.5 on 2023-01-12 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phim_TheLoaiPhim',
            new_name='Detail_Movie',
        ),
    ]
