# Generated by Django 4.1.5 on 2023-01-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_phim_theloaiphim_detail_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail_Movie',
            new_name='Movie_Detail',
        ),
    ]
