# Generated by Django 4.1.5 on 2023-01-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_detail_movie_movie_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_actor',
            old_name='dien_vien_id',
            new_name='director_id',
        ),
        migrations.RenameField(
            model_name='movie_actor',
            old_name='phim_id',
            new_name='movie_id',
        ),
    ]
