# Generated by Django 4.1.5 on 2023-01-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_dien_vien_id_movie_actor_director_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_pic',
            new_name='image',
        ),
    ]
