# Generated by Django 2.2 on 2023-04-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20230418_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='rating',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
