# Generated by Django 2.2 on 2023-03-08 08:52

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default/user.png', max_length=255, null=True, upload_to=information.models.Actor.image_upload_to)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors_name', models.CharField(max_length=255)),
                ('year_of_birth', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default/user.png', max_length=500, null=True, upload_to=information.models.Directors.image_upload_to)),
                ('descripton', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
