# Generated by Django 2.2 on 2023-01-13 05:58

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='default/user.png', max_length=255, null=True, upload_to=information.models.Actor.image_upload_to),
        ),
        migrations.AlterField(
            model_name='directors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='image',
            field=models.ImageField(default='default/user.png', max_length=500, null=True, upload_to=information.models.Directors.image_upload_to),
        ),
    ]
